name: ci
on:
    push:
        branches:
            - "main"
            - "dev"
        paths:
            - "**.py"
            - "pyproject.toml"
            - "poetry.lock"
            - ".github/workflows/**.yml"

jobs:
    checks:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - run: |
                  pip install poetry

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
                  cache: "poetry"

            # Install all deps. for pyright to be able to run type checking
            - run: poetry install

            # Lint with type checking
            - run: poetry pyright
            # - run: poetry run black --check .
            # - run: poetry run isort --check .

    # Update requirements.txt file (for non-poetry users) if the poetry dependencies change
    export-requirements:
        runs-on: ubuntu-latest
        needs: checks
        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - run: |
                  pip install poetry

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
                  cache: "poetry"

            - name: Generate requirements.txt
              run: poetry export -f requirements.txt --output requirements.txt --without-hashes

              # Check if the export changed anything in requirements.txt
            - name: Check for changes
              run: |
                  git add requirements.txt
                  if git diff --staged --exit-code -- requirements.txt; then
                      echo "No changes to requirements.txt"
                  else
                      echo "HAS_CHANGES=true" >> $GITHUB_ENV
                  fi
              continue-on-error: true

            - name: Commit changes
              uses: EndBug/add-and-commit@v9
              if: env.HAS_CHANGES == 'true'
              with:
                  message: "[Automated] Update requirements.txt"
                  add: "requirements.txt"
                  default_author: github_actions
